### ISSUE TITLE
Ready to use link broken

### ISSUE THREAD

**Issue by remisarrailh** [josephernest/bigpicture-editor#1]
The link for the ready-to-use package is broken.

I built it and make it available here : https://github.com/maditnerd/bigpicture-editor/releases/tag/1.0.1

I also added a bar to drag the window.
https://github.com/maditnerd/bigpicture-editor/commit/30c9741c47eff7b0513e376f7996f029fd635873
![image](https://user-images.githubusercontent.com/2841495/36979867-0d0f9d30-2089-11e8-8da1-b755a88bd2d5.png)

**Comment by josephernest** [comment]
Thanks @maditnerd! I fixed the link in the README file.
I'll try your version with title bar asap!
